ITALIAN_LEAGUES = [
    # 'serie-a',
    'serie-b',
    'serie-c-grione-a',
    # 'serie-c-grione-b',
    # 'serie-c-grione-c',
    ]

ITALIAN_CORRECT_NAMES = {
    'entella': 'virtus_entella',
    'san_donato' :'san_donato_tavarnelle',
    'sassari_torres': 'torres',
    'montevarchi': 'aquila_montevarchi',
    'Inter Milan': 'inter_milan',
    'internazionale': 'inter_milan',
    'inter': 'inter_milan',
    'internazionale': 'inter_milan',
    'verona': 'hellas_verona'
    }

ENGLISH_LEAGUES = [
    'premier-league',
    # 'championship',
    # 'league-one',
    # 'league-two',
    ]

ENGLISH_CORRECT_NAMES = {
    'AFC Bournemouth': 'Bournemouth',
    'Accrington Stanley': 'Accrington',
    'Arsenal': 'Arsenal',
    'Aston Villa': 'Aston Villa',
    'Barnsley': 'Barnsley',
    'Birmingham City': 'Birmingham',
    'Blackburn Rovers': 'Blackburn',
    'Blackpool': 'Blackpool',
    'Bolton Wanderers': 'Bolton',
    'Brentford': 'Brentford',
    'Bristol City': 'Bristol City',
    'Bristol Rovers': 'Bristol Rvs',
    'Burnley': 'Burnley',
    'Burton Albion': 'Burton',
    'Cambridge United': 'Cambridge',
    'Cardiff City': 'Cardiff',
    'Charlton Athletic': 'Charlton',
    'Chelsea': 'Chelsea',
    'Cheltenham Town': 'Cheltenham',
    'Coventry City': 'Coventry',
    'Crystal Palace': 'Crystal Palace',
    'Derby County': 'Derby',
    'Everton': 'Everton',
    'Exeter City': 'Exeter',
    'Fleetwood Town': 'Fleetwood Town',
    'Forest Green Rovers': 'Forest Green',
    'Fulham': 'Fulham',
    'Huddersfield Town': 'Huddersfield',
    'Hull City': 'Hull',
    'Ipswich Town': 'Ipswich',
    'Leeds United': 'Leeds',
    'Leicester City': 'Leicester',
    'Lincoln City': 'Lincoln',
    'Liverpool': 'Liverpool',
    'Luton Town': 'Luton',
    'Manchester City': 'Man City',
    'Manchester United': 'Man United',
    'Millwall': 'Millwall',
    'Middlesbrough': 'Middlesbrough',
    'MK Dons': 'Milton Keynes Dons',
    'Morecambe': 'Morecambe',
    'Newcastle United': 'Newcastle',
    'Norwich City': 'Norwich',
    'Nottingham Forest': 'Nott\'m Forest',
    'Oxford United': 'Oxford',
    'Peterborough United': 'Peterboro',
    'Plymouth Argyle': 'Plymouth',
    'Port Vale': 'Port Vale',
    'Portsmouth': 'Portsmouth',
    'Preston North End': 'Preston',
    'Queens Park Rangers': 'QPR',
    'Reading': 'Reading',
    'Rotherham United': 'Rotherham',
    'Sheffield United': 'Sheffield United',
    'Sheffield Wednesday': 'Sheffield Weds',
    'Shrewsbury Town': 'Shrewsbury',
    'Southampton': 'Southampton',
    'Stoke City': 'Stoke',
    'Sunderland': 'Sunderland',
    'Swansea City': 'Swansea',
    'Tottenham Hotspur': 'Tottenham',
    'Watford': 'Watford',
    'West Bromwich Albion': 'West Brom',
    'West Ham United': 'West Ham',
    'Wigan Athletic': 'Wigan',
    'Wolverhampton Wanderers': 'Wolves',
    'Wycombe Wanderers': 'Wycombe'
}