ITALIAN_LEAGUES = [
    'serie-a',
    # 'serie-b',
    # 'serie-c-group-a',
    # 'serie-c-group-b',
    # 'serie-c-group-c'
    ]

ITALIAN_CORRECT_NAMES = {
    'entella': 'virtus_entella',
    'san_donato' :'san_donato_tavarnelle',
    'sassari_torres': 'torres',
    'montevarchi': 'aquila_montevarchi',
    'Inter Milan': 'inter_milan',
    'internazionale': 'inter_milan',
    'inter': 'inter_milan',
    'internazionale': 'inter_milan',
    'verona': 'hellas_verona'
    }

ENGLISH_LEAGUES = [
    'premier-league',
    # 'championship',
    # 'league-one',
    # 'league-two',
    # 'national-league'
    ]

ENGLISH_CORRECT_NAMES = {
    'AFC Bournemouth': 'AFC Bournemouth',
    'Accrington Stanley': 'Accrington Stanley',
    'Arsenal': 'Arsenal',
    'Aston Villa': 'Aston Villa',
    'Barnsley': 'Barnsley',
    'Birmingham City': 'Birmingham City',
    'Blackburn Rovers': 'Blackburn Rovers',
    'Blackpool': 'Blackpool',
    'Bolton Wanderers': 'Bolton Wanderers',
    'Brentford': 'Brentford',
    'Bristol City': 'Bristol City',
    'Bristol Rovers': 'Bristol Rvs',
    'Burnley': 'Burnley',
    'Burton Albion': 'Burton',
    'Cambridge United': 'Cambridge',
    'Cardiff City': 'Cardiff City',
    'Charlton Athletic': 'Charlton Athletic',
    'Chelsea': 'Chelsea',
    'Cheltenham Town': 'Cheltenham',
    'Coventry City': 'Coventry City',
    'Crystal Palace': 'Crystal Palace',
    'Derby County': 'Derby',
    'Everton': 'Everton',
    'Exeter City': 'Exeter',
    'Fleetwood Town': 'Fleetwood Town',
    'Forest Green Rovers': 'Forest Green Rovers',
    'Fulham': 'Fulham',
    'Huddersfield Town': 'Huddersfield Town',
    'Hull City': 'Hull City',
    'Ipswich Town': 'Ipswich Town',
    'Leeds United': 'Leeds United',
    'Leicester City': 'Leicester City',
    'Lincoln City': 'Lincoln',
    'Liverpool': 'Liverpool',
    'Luton Town': 'Luton Town',
    'Manchester City': 'Manchester City',
    'Man City': 'Manchester City',
    'Manchester United': 'Manchester United',
    'Manchester Utd': 'Manchester United',
    'Man United': 'Manchester United',
    'Millwall': 'Millwall',
    'Middlesbrough': 'Middlesbrough',
    'MK Dons': 'Milton Keynes Dons',
    'Morecambe': 'Morecambe',
    'Newcastle United': 'Newcastle United',
    'Norwich City': 'Norwich City',
    'Nottingham Forest': 'Nott\'m Forest',
    'Oxford United': 'Oxford',
    'Peterborough United': 'Peterboro',
    'Plymouth Argyle': 'Plymouth',
    'Port Vale': 'Port Vale',
    'Portsmouth': 'Portsmouth',
    'Preston North End': 'Preston North End',
    'QPR': 'Queens Park Rangers',
    'Queens Park': 'Queens Park Rangers',
    'Queens Park Rangers': 'Queens Park Rangers',
    'Reading': 'Reading',
    'Rotherham United': 'Rotherham United',
    'Sheffield United': 'Sheffield United',
    'Sheffield Wed': 'Sheffield Wednesday',
    'Sheffield Weds': 'Sheffield Wednesday',
    'Sheffield Wednesday': 'Sheffield Wednesday',
    'Shrewsbury Town': 'Shrewsbury',
    'Southampton': 'Southampton',
    'Stoke City': 'Stoke City',
    'Sunderland': 'Sunderland',
    'Swansea City': 'Swansea City',
    'Tottenham Hotspur': 'Tottenham',
    'Watford': 'Watford',
    'West Bromwich Albion': 'West Bromwich Albion',
    'West Ham United': 'West Ham',
    'Wigan Athletic': 'Wigan Athletic',
    'Wolverhampton Wanderers': 'Wolves',
    'Wycombe Wanderers': 'Wycombe'
}

SCOTTISH_LEAGUES = [
    'premiership',
    'championship',
    'league-one',
]

SCOTTISH_CORRECT_NAMES = {}


####################################################################################################
# TEAMS FOR FULL SEASON SIMULATION
####################################################################################################

PREMIER_LEAGUE_TEAMS = [
    'Arsenal',
    'Aston Villa',
    'Bournemouth',
    'Brentford',
    'Brighton',
    'Chelsea',
    'Crystal Palace',
    'Everton',
    'Fulham',
    'Leeds',
    'Leicester',
    'Liverpool',
    'Manchester City',
    'Manchester United',
    'Newcastle',
    'Nottingham Forest',
    'Southampton',
    'Tottenham',
    'West Ham',
    'Wolves'
]

CHAMPIONSHIP_TEAMS = [
    'Birmingham City',
    'Blackburn Rovers',
    'Blackpool',
    'Bristol City',
    'Burnley',
    'Cardiff City',
    'Coventry City',
    'Huddersfield Town',
    'Hull City',
    'Luton Town',
    'Middlesbrough',
    'Millwall',
    'Norwich City',
    'Preston North End',
    'Queens Park Rangers',
    'Reading',
    'Rotherham United',
    'Sheffield United',
    'Stoke City',
    'Sunderland',
    'Swansea City',
    'West Bromwich Albion',
    'Watford',
    'Wigan Athletic'
]

LEAGUE_ONE_TEAMS = [
    'Accrington',
    'Barnsley',
    'Bolton',
    'Bristol Rovers',
    'Burton',
    'Cambridge',
    'Charlton',
    'Cheltenham',
    'Derby',
    'Exeter',
    'Fleetwood Town',
    'Forest Green',
    'Ipswich',
    'Lincoln',
    'Milton Keynes Dons',
    'Morecambe',
    'Oxford',
    'Peterborough',
    'Plymouth',
    'Portsmouth',
    'Port Vale',
    'Sheffield Wednesday',
    'Shrewsbury',
    'Wycombe'
]

LEAGUE_TWO_TEAMS = [
    'AFC Wimbledon',
    'Barrow',
    'Bradford',
    'Carlisle',
    'Colchester',
    'Crawley',
    'Crewe',
    'Doncaster',
    'Gillingham',
    'Grimsby',
    'Harrogate',
    'Hartlepool',
    'Leyton Orient',
    'Mansfield',
    'Newport',
    'Northampton',
    'Rochdale',
    'Salford',
    'Stevenage',
    'Stockport',
    'Sutton',
    'Swindon',
    'Tranmere',
    'Walsall'
]

SERIE_A_TEAMS = [
    'AC Milan',
    'Atalanta',
    'Bologna',
    'Cremonese',
    'Empoli',
    'Fiorentina',
    'Hella Verona',
    'Inter Milan',
    'Juventus',
    'Lazio',
    'Lecce',
    'Monza',
    'Napoli',
    'Roma',
    'Salernitana',
    'Sampdoria',
    'Sassuolo',
    'Spezia',
    'Torino',
    'Udinese'
]

SERIE_B_TEAMS = [
    'Ascoli',
    'Bari',
    'Benevento',
    'Brescia',
    'Cagliari',
    'Cittadella',
    'Como',
    'Cosenza',
    'Frosinone',
    'Genoa',
    'Modena',
    'Palermo',
    'Parma',
    'Perugia',
    'Pisa',
    'Reggina',
    'SPAL',
    'Sudtirol',
    'Ternana',
    'Venezia',
]

SERIE_C_GIRONE_A_TEAMS = [
    'Albinoleffe',
    'Arzignano',
    'Feralpisalo',
    'Juventus U23',
    'Lecco',
    'Mantova',
    'Novara',
    'Padova',
    'Pergolettese',
    'Piacenza',
    'Pordenone',
    'Pro Patria',
    'Pro Sesto',
    'Pro Vercelli',
    'Renate',
    'Sangiuliano',
    'Trento',
    'Triestina',
    'Vicenza',
    'Virtus Verona'
]

SERIE_C_GIRONE_B_TEAMS = [
    'Alessandria',
    'Ancona',
    'Aquilla Montevarchi',
    'Carrarese',
    'Cesena',
    'Entella',
    'Fermana',
    'Fiorenzuola',
    'Gubbio',
    'Imolese',
    'Lucchese',
    'Olbia',
    'Pontedera',
    'Recanatese',
    'Reggiana',
    'Rimini',
    'San Donato',
    'Siena',
    'Torres',
    'Vis Pesaro'
]

SERIE_C_GIRONE_C_TEAMS = [
    'Audace Cerignola',
    'Avellino',
    'AZ Picerno',
    'Catanzaro',
    'Crotone',
    'Fidelis Andria',
    'Foggia',
    'Gelbison',
    'Giugliano',
    'Juve Stabia',
    'Latina',
    'Messina',
    'Monopoli',
    'Monterosi',
    'Pescara',
    'Potenza',
    'Taranto',
    'Turris',
    'Virtus Francavilla',
    'Viterbese'
]

SCOTTISH_PREMIERSHIP_TEAMS = [
    'Aberdeen',
    'Celtic',
    'Dundee',
    'Hearts',
    'Hibernian',
    'Kilmarnock',
    'Livingston',
    'Motherwell',
    'Rangers',
    'Ross County',
    'St Johnstone',
    'St Mirren'
]

SCOTTISH_CHAMPIONSHIP_TEAMS = [
    'Airdrieonians',
    'Arbroath',
    'Ayr United',
    'Dundee United',
    'Dunfermline Athletic',
    'Morton',
    'Inverness Caledonian Thistle',
    'Partick Thistle',
    'Queen\'s Park',
    'Raith Rovers',
]

SCOTTISH_LEAGUE_ONE_TEAMS = [
    'Alloa Athletic',
    'Annan Athletic',
    'Cove Rangers',
    'Edinburgh City',
    'Falkirk',
    'Hamilton Academical',
    'Kelty Hearts',
    'Montrose',
    'Queen of the South',
    'Stirling Albion',
]

LEAGUE_TEAMS_MAPPING = {
    'Premier League': PREMIER_LEAGUE_TEAMS,
    'Championship': CHAMPIONSHIP_TEAMS,
    'League One': LEAGUE_ONE_TEAMS,
    'League Two': LEAGUE_TWO_TEAMS,
    'Serie A': SERIE_A_TEAMS,
    'Serie B': SERIE_B_TEAMS,
    'Serie C, Girone A': SERIE_C_GIRONE_A_TEAMS,
    'Serie C, Girone B': SERIE_C_GIRONE_B_TEAMS,
    'Serie C, Girone C': SERIE_C_GIRONE_C_TEAMS,
    'Scottish Premiership': SCOTTISH_PREMIERSHIP_TEAMS,
    'Scottish Championship': SCOTTISH_CHAMPIONSHIP_TEAMS,
    'Scottish League One': SCOTTISH_LEAGUE_ONE_TEAMS,
}