ITALIAN_LEAGUES = [
    'serie-a',
    # 'serie-b',
    # 'serie-c-group-a',
    'serie-c-group-b',
    # 'serie-c-group-c'
    ]

ITALIAN_CORRECT_NAMES = {
    'entella': 'virtus_entella',
    'san_donato' :'san_donato_tavarnelle',
    'sassari_torres': 'torres',
    'montevarchi': 'aquila_montevarchi',
    'Inter Milan': 'inter_milan',
    'internazionale': 'inter_milan',
    'inter': 'inter_milan',
    'internazionale': 'inter_milan',
    'verona': 'hellas_verona'
    }

ENGLISH_LEAGUES = [
    'premier-league',
    'championship',
    'league-one',
    'league-two',
    'national-league'
    ]

ENGLISH_CORRECT_NAMES = {
    'AFC Bournemouth': 'AFC Bournemouth',
    'Accrington Stanley': 'Accrington Stanley',
    'Arsenal': 'Arsenal',
    'Aston Villa': 'Aston Villa',
    'Barnsley': 'Barnsley',
    'Birmingham City': 'Birmingham City',
    'Blackburn': 'Blackburn Rovers',
    'Blackburn Rovers': 'Blackburn Rovers',
    'Blackpool': 'Blackpool',
    'Bolton': 'Bolton Wanderers',
    'Bolton Wanderers': 'Bolton Wanderers',
    'Brentford': 'Brentford',
    'Bristol City': 'Bristol City',
    'Bristol Rvs': 'Bristol Rovers',
    'Burnley': 'Burnley',
    'Burton': 'Burton Albion',
    'Cambridge': 'Cambridge United',
    'Cambridge Utd': 'Cambridge United',
    'Cardiff City': 'Cardiff City',
    'Carlisle': 'Carlisle United',
    'Charlton': 'Charlton Athletic',
    'Charlton Athletic': 'Charlton Athletic',
    'Chelsea': 'Chelsea',
    'Cheltenham': 'Cheltenham Town',
    'Coventry': 'Coventry City',
    'Coventry City': 'Coventry City',
    'Crystal Palace': 'Crystal Palace',
    'Dagenham & Redbridge': 'Dagenham and Redbridge',
    'Derby': 'Derby County',
    'Everton': 'Everton',
    'Exeter': 'Exeter City',
    'Fleetwood': 'Fleetwood Town',
    'Fleetwood Town': 'Fleetwood Town',
    'Forest Green Rovers': 'Forest Green Rovers',
    'Fulham': 'Fulham',
    'Huddersfield Town': 'Huddersfield Town',
    'Hull City': 'Hull City',
    'Ipswich': 'Ipswich Town',
    'Ipswich Town': 'Ipswich Town',
    'Leeds': 'Leeds United',
    'Leeds United': 'Leeds United',
    'Leicester': 'Leicester City',
    'Leicester City': 'Leicester City',
    'Lincoln City': 'Lincoln City',
    'Lincoln': 'Lincoln City',
    'Liverpool': 'Liverpool',
    'Luton': 'Luton Town',
    'Luton Town': 'Luton Town',
    'Manchester City': 'Manchester City',
    'Man City': 'Manchester City',
    'Manchester United': 'Manchester United',
    'Manchester Utd': 'Manchester United',
    'Man United': 'Manchester United',
    'Millwall': 'Millwall',
    'Middlesbrough': 'Middlesbrough',
    'MK Dons': 'Milton Keynes Dons',
    'Morecambe': 'Morecambe',
    'Newcastle United': 'Newcastle United',
    'Northampton': 'Northampton Town',
    'Norwich City': 'Norwich City',
    'Nott\'m Forest': 'Nottingham Forest',
    'Oxford': 'Oxford United',
    'Oxford Utd': 'Oxford United',
    'Peterboro': 'Peterborough United',
    'Peterborough': 'Peterborough United',
    'Plymouth': 'Plymouth Argyle',
    'Port Vale': 'Port Vale',
    'Portsmouth': 'Portsmouth',
    'PNE': 'Preston North End',
    'Preston': 'Preston North End',
    'Preston North End': 'Preston North End',
    'QPR': 'Queens Park Rangers',
    'Queens Park': 'Queens Park Rangers',
    'Queens Park Rangers': 'Queens Park Rangers',
    'Oxford': 'Oxford United',
    'Oxford Utd': 'Oxford United',
    'Reading': 'Reading',
    'Rotherham United': 'Rotherham United',
    'Sheffield United': 'Sheffield United',
    'Sheffield Wed': 'Sheffield Wednesday',
    'Sheffield Weds': 'Sheffield Wednesday',
    'Sheffield Wednesday': 'Sheffield Wednesday',
    'Shrewsbury': 'Shrewsbury Town',
    'Southampton': 'Southampton',
    'Stoke City': 'Stoke City',
    'Sunderland': 'Sunderland',
    'Swansea City': 'Swansea City',
    'Swindon': 'Swindon Town',
    'Tottenham': 'Tottenham Hotspur',
    'Watford': 'Watford',
    'West Bromwich Albion': 'West Bromwich Albion',
    'West Ham': 'West Ham United',
    'Wigan': 'Wigan Athletic',
    'Wigan Athletic': 'Wigan Athletic',
    'Wolves': 'Wolverhampton Wanderers',
    'Wycombe': 'Wycombe Wanderers'
}

SCOTTISH_LEAGUES = [
    # 'premiership',
    # 'championship',
    # 'league-one',
]

SCOTTISH_CORRECT_NAMES = {}


####################################################################################################
# TEAMS FOR FULL SEASON SIMULATION
####################################################################################################

PREMIER_LEAGUE_TEAMS = [
    'Arsenal',
    'Aston Villa',
    'Bournemouth',
    'Brentford',
    'Brighton',
    'Burnley',
    'Chelsea',
    'Crystal Palace',
    'Everton',
    'Fulham',
    'Liverpool',
    'Luton Town',
    'Manchester City',
    'Manchester United',
    'Newcastle United',
    'Nottingham Forest',
    'Sheffield United',
    'Tottenham Hotspur',
    'West Ham United',
    'Wolverhampton Wanderers'
]

CHAMPIONSHIP_TEAMS = [
    'Birmingham City',
    'Blackburn Rovers',
    'Bristol City',
    'Cardiff City',
    'Coventry City',
    'Huddersfield Town',
    'Hull City',
    'Ipswich Town',
    'Leeds United',
    'Leicester City',
    'Middlesbrough',
    'Millwall',
    'Norwich City',
    'Plymouth Argyle',
    'Preston North End',
    'Queens Park Rangers',
    'Rotherham United',
    'Sheffield Wednesday',
    'Southampton',
    'Stoke City',
    'Sunderland',
    'Swansea City',
    'West Bromwich Albion',
    'Watford',
]

LEAGUE_ONE_TEAMS = [
    'Barnsley',
    'Blackpool',
    'Bolton Wanderers',
    'Bristol Rovers',
    'Burton Albion',
    'Cambridge United',
    'Carlisle United',
    'Charlton Athletic',
    'Cheltenham Town',
    'Derby County',
    'Exeter City',
    'Fleetwood Town',
    'Leyton Orient',
    'Lincoln City',
    'Northampton Town',
    'Oxford United',
    'Peterborough United',
    'Portsmouth',
    'Port Vale',
    'Reading',
    'Shrewsbury Town',
    'Stevenage',
    'Wigan Athletic',
    'Wycombe Wanderers'
]

LEAGUE_TWO_TEAMS = [
    'Accrington Stanley',
    'AFC Wimbledon',
    'Barrow',
    'Bradford City',
    'Colchester United',
    'Crawley Town',
    'Crewe Alexandra',
    'Doncaster Rovers',
    'Forest Green Rovers',
    'Gillingham',
    'Grimsby Town',
    'Harrogate Town',
    'Mansfield Town',
    'Milton Keynes Dons',
    'Morecambe',
    'Newport County',
    'Notts County',
    'Salford City',
    'Stockport County',
    'Sutton United',
    'Swindon Town',
    'Tranmere Rovers',
    'Walsall',
    'Wrexham'
]

NATIONAL_LEAGUE_TEAMS = [
    'AFC Fylde',
    'Aldershot Town',
    'Altrincham',
    'Barnet',
    'Boreham Wood',
    'Bromley',
    'Chesterfield',
    'Dagenham and Redbridge',
    'Dorking Wanderers',
    'Eastleigh',
    'Ebbsfleet United',
    'FC Halifax Town',
    'Gateshead',
    'Hartlepool United',
    'Kiddyminster Harriers',
    'Maidenhead United',
    'Oldham Athletic',
    'Oxford City',
    'Rochdale',
    'Solihull Moors',
    'Southend United',
    'Wealdstone',
    'Woking',
    'York City'
]

SERIE_A_TEAMS = [
    'AC Milan',
    'Atalanta',
    'Bologna',
    'Cremonese',
    'Empoli',
    'Fiorentina',
    'Hella Verona',
    'Inter Milan',
    'Juventus',
    'Lazio',
    'Lecce',
    'Monza',
    'Napoli',
    'Roma',
    'Salernitana',
    'Sampdoria',
    'Sassuolo',
    'Spezia',
    'Torino',
    'Udinese'
]

SERIE_B_TEAMS = [
    'Ascoli',
    'Bari',
    'Benevento',
    'Brescia',
    'Cagliari',
    'Cittadella',
    'Como',
    'Cosenza',
    'Frosinone',
    'Genoa',
    'Modena',
    'Palermo',
    'Parma',
    'Perugia',
    'Pisa',
    'Reggina',
    'SPAL',
    'Sudtirol',
    'Ternana',
    'Venezia',
]

SERIE_C_GIRONE_A_TEAMS = [
    'Albinoleffe',
    'Arzignano',
    'Feralpisalo',
    'Juventus U23',
    'Lecco',
    'Mantova',
    'Novara',
    'Padova',
    'Pergolettese',
    'Piacenza',
    'Pordenone',
    'Pro Patria',
    'Pro Sesto',
    'Pro Vercelli',
    'Renate',
    'Sangiuliano',
    'Trento',
    'Triestina',
    'Vicenza',
    'Virtus Verona'
]

SERIE_C_GIRONE_B_TEAMS = [
    'Alessandria',
    'Ancona',
    'Aquilla Montevarchi',
    'Carrarese',
    'Cesena',
    'Entella',
    'Fermana',
    'Fiorenzuola',
    'Gubbio',
    'Imolese',
    'Lucchese',
    'Olbia',
    'Pontedera',
    'Recanatese',
    'Reggiana',
    'Rimini',
    'San Donato',
    'Siena',
    'Torres',
    'Vis Pesaro'
]

SERIE_C_GIRONE_C_TEAMS = [
    'Audace Cerignola',
    'Avellino',
    'AZ Picerno',
    'Catanzaro',
    'Crotone',
    'Fidelis Andria',
    'Foggia',
    'Gelbison',
    'Giugliano',
    'Juve Stabia',
    'Latina',
    'Messina',
    'Monopoli',
    'Monterosi',
    'Pescara',
    'Potenza',
    'Taranto',
    'Turris',
    'Virtus Francavilla',
    'Viterbese'
]

SCOTTISH_PREMIERSHIP_TEAMS = [
    'Aberdeen',
    'Celtic',
    'Dundee',
    'Hearts',
    'Hibernian',
    'Kilmarnock',
    'Livingston',
    'Motherwell',
    'Rangers',
    'Ross County',
    'St Johnstone',
    'St Mirren'
]

SCOTTISH_CHAMPIONSHIP_TEAMS = [
    'Airdrieonians',
    'Arbroath',
    'Ayr United',
    'Dundee United',
    'Dunfermline Athletic',
    'Morton',
    'Inverness Caledonian Thistle',
    'Partick Thistle',
    'Queen\'s Park',
    'Raith Rovers',
]

SCOTTISH_LEAGUE_ONE_TEAMS = [
    'Alloa Athletic',
    'Annan Athletic',
    'Cove Rangers',
    'Edinburgh City',
    'Falkirk',
    'Hamilton Academical',
    'Kelty Hearts',
    'Montrose',
    'Queen of the South',
    'Stirling Albion',
]

LEAGUE_TEAMS_MAPPING = {
    'Premier League': PREMIER_LEAGUE_TEAMS,
    'Championship': CHAMPIONSHIP_TEAMS,
    'League One': LEAGUE_ONE_TEAMS,
    'League Two': LEAGUE_TWO_TEAMS,
    'National League': NATIONAL_LEAGUE_TEAMS,
    'Serie A': SERIE_A_TEAMS,
    # 'Serie B': SERIE_B_TEAMS,
    # 'Serie C, Girone A': SERIE_C_GIRONE_A_TEAMS,
    # 'Serie C, Girone B': SERIE_C_GIRONE_B_TEAMS,
    # 'Serie C, Girone C': SERIE_C_GIRONE_C_TEAMS,
    # 'Scottish Premiership': SCOTTISH_PREMIERSHIP_TEAMS,
    # 'Scottish Championship': SCOTTISH_CHAMPIONSHIP_TEAMS,
    # 'Scottish League One': SCOTTISH_LEAGUE_ONE_TEAMS,
}